// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.

export const componentList: Array<{ name: string; title: string; category: string; tags: string[] }> = [

]
