import { promises as fs } from 'fs'
import path from 'path'

const REGISTRY_BASE = path.join(process.cwd(), 'registry', 'components')
const BLOCKS_BASE = path.join(process.cwd(), 'registry', 'blocks')
const INDEX_OUTPUT = path.join(process.cwd(), 'registry', '__index__.tsx')
const COMPONENT_LIST_OUTPUT = path.join(process.cwd(), 'registry', 'component-list.ts')
const BLOCK_LIST_OUTPUT = path.join(process.cwd(), 'registry', 'block-list.ts')
const REGISTRY_JSON_OUTPUT = path.join(process.cwd(), 'public', 'registry.json')
const SKILL_REFS_DIR = path.join(process.cwd(), '..', '..', 'skills', 'vritti-ui', 'references')

const CATEGORIES = [
  'animations',
  'backgrounds',
  'text',
  'buttons',
  'cards',
  'layouts',
  'navigation',
  'carousels',
  'cursors',
  'inputs',
  'media',
  'special',
]

const BLOCK_CATEGORIES = [
  'hero',
  'pricing',
  'auth',
  'testimonial',
  'contact',
  'faq',
  'footer',
  'blog',
  'ecommerce',
  'billing',
  'modal',
  'account',
  'navigation',
  'cards',
  'gallery',
  'features',
  'cta',
  'special',
]

function toTitleCase(str: string): string {
  return str
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

interface ComponentMeta {
  name: string
  title: string
  description: string
  category: string
  type: 'component' | 'block'
  dependencies?: string[]
  registryDependencies?: string[]
  meta?: Record<string, unknown>
}

async function scanDirectory(basePath: string, categories: string[], itemType: 'component' | 'block'): Promise<ComponentMeta[]> {
  const items: ComponentMeta[] = []

  for (const category of categories) {
    const categoryPath = path.join(basePath, category)
    let entries: string[]
    try {
      entries = await fs.readdir(categoryPath)
    } catch {
      continue
    }

    for (const name of entries) {
      const componentDir = path.join(categoryPath, name)
      const stat = await fs.stat(componentDir)
      if (!stat.isDirectory()) continue

      // Read component.json for metadata
      let metadata: Record<string, unknown> = {}
      try {
        const jsonContent = await fs.readFile(
          path.join(componentDir, 'component.json'),
          'utf-8'
        )
        metadata = JSON.parse(jsonContent)
      } catch {
        // Use defaults if no component.json
      }

      // Check if component.tsx exists
      const hasComponent = await fs
        .access(path.join(componentDir, 'component.tsx'))
        .then(() => true)
        .catch(() => false)

      if (!hasComponent) continue

      items.push({
        name,
        title: (metadata.title as string) || toTitleCase(name),
        description: (metadata.description as string) || `${toTitleCase(name)} ${itemType}.`,
        category,
        type: itemType,
        dependencies: metadata.dependencies as string[] | undefined,
        registryDependencies: metadata.registryDependencies as string[] | undefined,
        meta: metadata.meta as Record<string, unknown> | undefined,
      })
    }
  }

  return items.sort((a, b) => a.name.localeCompare(b.name))
}

async function buildRegistryIndex(components: ComponentMeta[], blocks: ComponentMeta[]) {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`

  // Build component entries
  for (const comp of components) {
    const componentRelPath = `registry/components/${comp.category}/${comp.name}/component.tsx`
    const exampleRelPath = `registry/components/${comp.category}/${comp.name}/example.tsx`
    const componentImportPath = `@/registry/components/${comp.category}/${comp.name}/component`
    const exampleImportPath = `@/registry/components/${comp.category}/${comp.name}/example`

    const hasExample = await fs
      .access(
        path.join(REGISTRY_BASE, comp.category, comp.name, 'example.tsx')
      )
      .then(() => true)
      .catch(() => false)

    // Scan for additional example files (example-*.tsx)
    const compDir = path.join(REGISTRY_BASE, comp.category, comp.name)
    const compFiles = await fs.readdir(compDir)
    const extraExamples = compFiles
      .filter(f => f.startsWith('example-') && f.endsWith('.tsx'))
      .map(f => f.replace('.tsx', ''))
      .sort()

    index += `
  "${comp.name}": {
    name: "${comp.name}",
    description: "${(comp.description || '').replace(/"/g, '\\"')}",
    type: "registry:ui",
    category: "${comp.category}",
    registryDependencies: ${JSON.stringify(comp.registryDependencies || undefined)},
    dependencies: ${JSON.stringify(comp.dependencies || [])},
    files: [{
      path: "${componentRelPath}",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("${componentImportPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object')
      return { default: mod.default || mod[exportName] }
    }),
    meta: ${JSON.stringify(comp.meta)},
  },`

    if (hasExample) {
      index += `
  "${comp.name}-demo": {
    name: "${comp.name}-demo",
    description: "${(comp.description || '').replace(/"/g, '\\"')} (demo)",
    type: "registry:example",
    category: "${comp.category}",
    registryDependencies: ["${comp.name}"],
    files: [{
      path: "${exampleRelPath}",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("${exampleImportPath}")),
    meta: ${JSON.stringify(comp.meta)},
  },`
    }

    // Register additional examples
    for (const exName of extraExamples) {
      const exRelPath = `registry/components/${comp.category}/${comp.name}/${exName}.tsx`
      const exImportPath = `@/registry/components/${comp.category}/${comp.name}/${exName}`
      const registryKey = `${comp.name}-${exName.replace('example-', '')}`
      index += `
  "${registryKey}": {
    name: "${registryKey}",
    description: "${(comp.description || '').replace(/"/g, '\\"')} (${exName.replace('example-', '')})",
    type: "registry:example",
    category: "${comp.category}",
    registryDependencies: ["${comp.name}"],
    files: [{
      path: "${exRelPath}",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("${exImportPath}")),
    meta: ${JSON.stringify(comp.meta)},
  },`
    }
  }

  // Build block entries
  for (const block of blocks) {
    const componentRelPath = `registry/blocks/${block.category}/${block.name}/component.tsx`
    const exampleRelPath = `registry/blocks/${block.category}/${block.name}/example.tsx`
    const componentImportPath = `@/registry/blocks/${block.category}/${block.name}/component`
    const exampleImportPath = `@/registry/blocks/${block.category}/${block.name}/example`

    const hasExample = await fs
      .access(
        path.join(BLOCKS_BASE, block.category, block.name, 'example.tsx')
      )
      .then(() => true)
      .catch(() => false)

    // Scan for additional example files (example-*.tsx)
    const blockDir = path.join(BLOCKS_BASE, block.category, block.name)
    const blockFiles = await fs.readdir(blockDir)
    const extraBlockExamples = blockFiles
      .filter(f => f.startsWith('example-') && f.endsWith('.tsx'))
      .map(f => f.replace('.tsx', ''))
      .sort()

    index += `
  "${block.name}": {
    name: "${block.name}",
    description: "${(block.description || '').replace(/"/g, '\\"')}",
    type: "registry:block",
    category: "${block.category}",
    registryDependencies: ${JSON.stringify(block.registryDependencies || undefined)},
    dependencies: ${JSON.stringify(block.dependencies || [])},
    files: [{
      path: "${componentRelPath}",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("${componentImportPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object')
      return { default: mod.default || mod[exportName] }
    }),
    meta: ${JSON.stringify(block.meta)},
  },`

    if (hasExample) {
      index += `
  "${block.name}-demo": {
    name: "${block.name}-demo",
    description: "${(block.description || '').replace(/"/g, '\\"')} (demo)",
    type: "registry:example",
    category: "${block.category}",
    registryDependencies: ["${block.name}"],
    files: [{
      path: "${exampleRelPath}",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("${exampleImportPath}")),
    meta: ${JSON.stringify(block.meta)},
  },`
    }

    // Register additional examples for blocks
    for (const exName of extraBlockExamples) {
      const exRelPath = `registry/blocks/${block.category}/${block.name}/${exName}.tsx`
      const exImportPath = `@/registry/blocks/${block.category}/${block.name}/${exName}`
      const registryKey = `${block.name}-${exName.replace('example-', '')}`
      index += `
  "${registryKey}": {
    name: "${registryKey}",
    description: "${(block.description || '').replace(/"/g, '\\"')} (${exName.replace('example-', '')})",
    type: "registry:example",
    category: "${block.category}",
    registryDependencies: ["${block.name}"],
    files: [{
      path: "${exRelPath}",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("${exImportPath}")),
    meta: ${JSON.stringify(block.meta)},
  },`
    }
  }

  index += `
}
`

  await fs.writeFile(INDEX_OUTPUT, index, 'utf-8')
  console.log(
    `Registry index built: ${components.length} components + ${blocks.length} blocks -> ${INDEX_OUTPUT}`
  )
}

async function buildComponentList(components: ComponentMeta[]) {
  const entries = components.map(
    (c) => {
      const tags = (c.meta?.tags as string[] | undefined) || []
      return `  { name: "${c.name}", title: "${c.title.replace(/"/g, '\\"')}", category: "${c.category}", tags: ${JSON.stringify(tags)} },`
    }
  )

  const content = `// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.

export const componentList: Array<{ name: string; title: string; category: string; tags: string[] }> = [
${entries.join('\n')}
]
`

  await fs.writeFile(COMPONENT_LIST_OUTPUT, content, 'utf-8')
  console.log(`Component list built: ${components.length} entries -> ${COMPONENT_LIST_OUTPUT}`)
}

async function buildBlockList(blocks: ComponentMeta[]) {
  const entries = blocks.map(
    (b) =>
      `  { name: "${b.name}", title: "${b.title.replace(/"/g, '\\"')}", category: "${b.category}" },`
  )

  const content = `// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.

export const blockList: Array<{ name: string; title: string; category: string }> = [
${entries.join('\n')}
]
`

  await fs.writeFile(BLOCK_LIST_OUTPUT, content, 'utf-8')
  console.log(`Block list built: ${blocks.length} entries -> ${BLOCK_LIST_OUTPUT}`)
}


async function buildRegistryJson(components: ComponentMeta[], blocks: ComponentMeta[]) {
  const items: Record<string, unknown>[] = []

  // Process components
  for (const comp of components) {
    const compDir = path.join(REGISTRY_BASE, comp.category, comp.name)

    const tags = (comp.meta?.tags as string[] | undefined) || []

    items.push({
      name: comp.name,
      type: 'registry:ui',
      title: comp.title,
      description: comp.description,
      dependencies: comp.dependencies || [],
      registryDependencies: comp.registryDependencies || [],
      files: [{
        path: `registry/components/${comp.category}/${comp.name}/${comp.name}.tsx`,
        type: 'registry:ui',
        target: `components/vritti/${comp.name}.tsx`,
      }],
      categories: [comp.category, ...tags],
      meta: comp.meta || {},
    })

    // Add example items
    const compFiles = await fs.readdir(compDir)
    const hasExample = compFiles.includes('example.tsx')
    if (hasExample) {
      items.push({
        name: `${comp.name}-demo`,
        type: 'registry:example',
        title: `${comp.title} Demo`,
        description: `${comp.description} (demo)`,
        registryDependencies: [comp.name],
        files: [{
          path: `registry/components/${comp.category}/${comp.name}/example.tsx`,
          type: 'registry:example',
        }],
        categories: [comp.category],
      })
    }

    // Add extra examples
    const extraExamples = compFiles
      .filter(f => f.startsWith('example-') && f.endsWith('.tsx'))
      .sort()
    for (const exFile of extraExamples) {
      const variant = exFile.replace('example-', '').replace('.tsx', '')
      items.push({
        name: `${comp.name}-${variant}`,
        type: 'registry:example',
        title: `${comp.title} (${toTitleCase(variant)})`,
        description: `${comp.description} (${variant})`,
        registryDependencies: [comp.name],
        files: [{
          path: `registry/components/${comp.category}/${comp.name}/${exFile}`,
          type: 'registry:example',
        }],
        categories: [comp.category],
      })
    }
  }

  // Process blocks
  for (const block of blocks) {
    const blockDir = path.join(BLOCKS_BASE, block.category, block.name)

    items.push({
      name: block.name,
      type: 'registry:block',
      title: block.title,
      description: block.description,
      dependencies: block.dependencies || [],
      registryDependencies: block.registryDependencies || [],
      files: [{
        path: `registry/blocks/${block.category}/${block.name}/${block.name}.tsx`,
        type: 'registry:block',
        target: `components/vritti/blocks/${block.name}.tsx`,
      }],
      categories: [block.category],
      meta: block.meta || {},
    })

    // Add block examples
    const blockFiles = await fs.readdir(blockDir)
    const hasExample = blockFiles.includes('example.tsx')
    if (hasExample) {
      items.push({
        name: `${block.name}-demo`,
        type: 'registry:example',
        title: `${block.title} Demo`,
        description: `${block.description} (demo)`,
        registryDependencies: [block.name],
        files: [{
          path: `registry/blocks/${block.category}/${block.name}/example.tsx`,
          type: 'registry:example',
        }],
        categories: [block.category],
      })
    }

    const extraBlockExamples = blockFiles
      .filter(f => f.startsWith('example-') && f.endsWith('.tsx'))
      .sort()
    for (const exFile of extraBlockExamples) {
      const variant = exFile.replace('example-', '').replace('.tsx', '')
      items.push({
        name: `${block.name}-${variant}`,
        type: 'registry:example',
        title: `${block.title} (${toTitleCase(variant)})`,
        description: `${block.description} (${variant})`,
        registryDependencies: [block.name],
        files: [{
          path: `registry/blocks/${block.category}/${block.name}/${exFile}`,
          type: 'registry:example',
        }],
        categories: [block.category],
      })
    }
  }

  const registry = {
    $schema: 'https://ui.shadcn.com/schema/registry.json',
    name: 'vritti',
    homepage: 'https://vritti.thesatyajit.com',
    items,
  }

  await fs.writeFile(REGISTRY_JSON_OUTPUT, JSON.stringify(registry, null, 2), 'utf-8')
  console.log(`Registry JSON built: ${items.length} items -> ${REGISTRY_JSON_OUTPUT}`)
}

async function buildSkillReferences(components: ComponentMeta[], blocks: ComponentMeta[]) {
  await fs.mkdir(SKILL_REFS_DIR, { recursive: true })

  // Build component catalog
  let componentCatalog = `# Vritti UI Component Catalog\n\n`
  componentCatalog += `> Auto-generated from the registry. ${components.length} components across ${CATEGORIES.length} categories.\n\n`

  const componentsByCategory = new Map<string, ComponentMeta[]>()
  for (const comp of components) {
    const list = componentsByCategory.get(comp.category) || []
    list.push(comp)
    componentsByCategory.set(comp.category, list)
  }

  for (const category of CATEGORIES) {
    const items = componentsByCategory.get(category) || []
    if (items.length === 0) continue
    componentCatalog += `## ${toTitleCase(category)} (${items.length})\n\n`
    componentCatalog += `| Component | Description | Dependencies |\n`
    componentCatalog += `|-----------|-------------|-------------|\n`
    for (const item of items) {
      const deps = (item.dependencies || []).join(', ') || '-'
      componentCatalog += `| [${item.title}](https://vritti.thesatyajit.com/docs/components/${item.name}) | ${item.description.replace(/\|/g, '\\|')} | ${deps} |\n`
    }
    componentCatalog += `\n`
  }

  await fs.writeFile(path.join(SKILL_REFS_DIR, 'component-catalog.md'), componentCatalog, 'utf-8')

  // Build block catalog
  let blockCatalog = `# Vritti UI Block Catalog\n\n`
  blockCatalog += `> Auto-generated from the registry. ${blocks.length} blocks across ${BLOCK_CATEGORIES.length} categories.\n\n`

  const blocksByCategory = new Map<string, ComponentMeta[]>()
  for (const block of blocks) {
    const list = blocksByCategory.get(block.category) || []
    list.push(block)
    blocksByCategory.set(block.category, list)
  }

  for (const category of BLOCK_CATEGORIES) {
    const items = blocksByCategory.get(category) || []
    if (items.length === 0) continue
    blockCatalog += `## ${toTitleCase(category)} (${items.length})\n\n`
    blockCatalog += `| Block | Description | Dependencies |\n`
    blockCatalog += `|-------|-------------|-------------|\n`
    for (const item of items) {
      const deps = (item.dependencies || []).join(', ') || '-'
      blockCatalog += `| [${item.title}](https://vritti.thesatyajit.com/docs/blocks/${item.name}) | ${item.description.replace(/\|/g, '\\|')} | ${deps} |\n`
    }
    blockCatalog += `\n`
  }

  await fs.writeFile(path.join(SKILL_REFS_DIR, 'block-catalog.md'), blockCatalog, 'utf-8')
  console.log(`Skill references built -> ${SKILL_REFS_DIR}`)
}

async function main() {
  console.log('Scanning components...')
  const components = await scanDirectory(REGISTRY_BASE, CATEGORIES, 'component')
  console.log(`Found ${components.length} components across ${CATEGORIES.length} categories`)

  console.log('Scanning blocks...')
  const blocks = await scanDirectory(BLOCKS_BASE, BLOCK_CATEGORIES, 'block')
  console.log(`Found ${blocks.length} blocks across ${BLOCK_CATEGORIES.length} categories`)

  await buildRegistryIndex(components, blocks)
  await buildComponentList(components)
  await buildBlockList(blocks)
  await buildRegistryJson(components, blocks)
  await buildSkillReferences(components, blocks)

  console.log('Done!')
}

main().catch((error) => {
  console.error('Failed to build registry:', error)
  process.exit(1)
})
