// Theme presets extracted from tweakcn (https://tweakcn.com)
// All colors are in hex (#rrggbb) format for the Vritti theme editor.

export interface ThemeColors {
  background: string;
  foreground: string;
  card: string;
  'card-foreground': string;
  popover: string;
  'popover-foreground': string;
  primary: string;
  'primary-foreground': string;
  secondary: string;
  'secondary-foreground': string;
  muted: string;
  'muted-foreground': string;
  accent: string;
  'accent-foreground': string;
  destructive: string;
  'destructive-foreground': string;
  border: string;
  input: string;
  ring: string;
  'chart-1': string;
  'chart-2': string;
  'chart-3': string;
  'chart-4': string;
  'chart-5': string;
  // Note: tweakcn uses 'sidebar' but we maintain backward compatibility with 'sidebar-background'
  'sidebar-background': string;
  'sidebar-foreground': string;
  'sidebar-primary': string;
  'sidebar-primary-foreground': string;
  'sidebar-accent': string;
  'sidebar-accent-foreground': string;
  'sidebar-border': string;
  'sidebar-ring': string;
}

export interface ThemePreset {
  name: string;
  label: string;
  createdAt?: string;
  config: {
    light: ThemeColors;
    dark: ThemeColors;
    radius: string;
  };
  // Store fonts separately in our structure
  fonts?: {
    sans?: string;
    serif?: string;
    mono?: string;
  };
  // Optional shadow properties from tweakcn
  shadow?: {
    color?: string;
    opacity?: string;
    blur?: string;
    spread?: string;
    offsetX?: string;
    offsetY?: string;
  };
  // Optional letter spacing and spacing
  letterSpacing?: string;
  spacing?: string;
}

// Helper function to convert tweakcn format (with 'sidebar') to our format (with 'sidebar-background')
function convertTweakcnToVritti(tweakcnColors: Record<string, string>): ThemeColors {
  const {
    sidebar,
    'sidebar-foreground': sidebarForeground,
    'sidebar-primary': sidebarPrimary,
    'sidebar-primary-foreground': sidebarPrimaryForeground,
    'sidebar-accent': sidebarAccent,
    'sidebar-accent-foreground': sidebarAccentForeground,
    'sidebar-border': sidebarBorder,
    'sidebar-ring': sidebarRing,
    ...rest
  } = tweakcnColors;

  return {
    'sidebar-background': sidebar || '#ffffff',
    'sidebar-foreground': sidebarForeground || '#000000',
    'sidebar-primary': sidebarPrimary || '#000000',
    'sidebar-primary-foreground': sidebarPrimaryForeground || '#ffffff',
    'sidebar-accent': sidebarAccent || '#f0f0f0',
    'sidebar-accent-foreground': sidebarAccentForeground || '#000000',
    'sidebar-border': sidebarBorder || '#e5e5e5',
    'sidebar-ring': sidebarRing || '#000000',
    ...rest,
  } as ThemeColors;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    name: 'modern-minimal',
    label: 'Modern Minimal',
    config: {
      light: convertTweakcnToVritti({
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0f2fe',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
      }),
      dark: convertTweakcnToVritti({
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        'chart-1': '#60a5fa',
        'chart-2': '#3b82f6',
        'chart-3': '#2563eb',
        'chart-4': '#1d4ed8',
        'chart-5': '#1e40af',
        sidebar: '#171717',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1e3a8a',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#404040',
        'sidebar-ring': '#3b82f6',
      }),
      radius: '0.375rem',
    },
    fonts: {
      sans: 'Inter, sans-serif',
      serif: 'Source Serif 4, serif',
      mono: 'JetBrains Mono, monospace',
    },
  },
  {
    name: 'violet-bloom',
    label: 'Violet Bloom',
    createdAt: '2025-06-26',
    config: {
      light: convertTweakcnToVritti({
        background: '#fdfdfd',
        foreground: '#000000',
        card: '#fdfdfd',
        'card-foreground': '#000000',
        popover: '#fcfcfc',
        'popover-foreground': '#000000',
        primary: '#7033ff',
        'primary-foreground': '#ffffff',
        secondary: '#edf0f4',
        'secondary-foreground': '#080808',
        muted: '#f5f5f5',
        'muted-foreground': '#525252',
        accent: '#e2ebff',
        'accent-foreground': '#1e69dc',
        destructive: '#e54b4f',
        'destructive-foreground': '#ffffff',
        border: '#e7e7ee',
        input: '#ebebeb',
        ring: '#000000',
        'chart-1': '#4ac885',
        'chart-2': '#7033ff',
        'chart-3': '#fd822b',
        'chart-4': '#3276e4',
        'chart-5': '#747474',
        sidebar: '#f5f8fb',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#000000',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#ebebeb',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#000000',
      }),
      dark: convertTweakcnToVritti({
        background: '#1a1b1e',
        foreground: '#f0f0f0',
        card: '#222327',
        'card-foreground': '#f0f0f0',
        popover: '#222327',
        'popover-foreground': '#f0f0f0',
        primary: '#8c5cff',
        'primary-foreground': '#ffffff',
        secondary: '#2a2c33',
        'secondary-foreground': '#f0f0f0',
        muted: '#2a2c33',
        'muted-foreground': '#a0a0a0',
        accent: '#1e293b',
        'accent-foreground': '#79c0ff',
        destructive: '#f87171',
        'destructive-foreground': '#ffffff',
        border: '#33353a',
        input: '#33353a',
        ring: '#8c5cff',
        'chart-1': '#4ade80',
        'chart-2': '#8c5cff',
        'chart-3': '#fca5a5',
        'chart-4': '#5993f4',
        'chart-5': '#a0a0a0',
        sidebar: '#161618',
        'sidebar-foreground': '#f0f0f0',
        'sidebar-primary': '#8c5cff',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a2c33',
        'sidebar-accent-foreground': '#8c5cff',
        'sidebar-border': '#33353a',
        'sidebar-ring': '#8c5cff',
      }),
      radius: '1.4rem',
    },
    fonts: {
      sans: 'Plus Jakarta Sans, sans-serif',
      serif: 'Lora, serif',
      mono: 'IBM Plex Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.16',
      blur: '3px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '2px',
    },
    letterSpacing: '-0.025em',
    spacing: '0.27rem',
  },
  {
    name: 't3-chat',
    label: 'T3 Chat',
    createdAt: '2025-04-19',
    config: {
      light: convertTweakcnToVritti({
        background: '#faf5fa',
        foreground: '#501854',
        card: '#faf5fa',
        'card-foreground': '#501854',
        popover: '#ffffff',
        'popover-foreground': '#501854',
        primary: '#a84370',
        'primary-foreground': '#ffffff',
        secondary: '#f1c4e6',
        'secondary-foreground': '#77347c',
        muted: '#f6e5f3',
        'muted-foreground': '#834588',
        accent: '#f1c4e6',
        'accent-foreground': '#77347c',
        destructive: '#ab4347',
        'destructive-foreground': '#ffffff',
        border: '#efbdeb',
        input: '#e7c1dc',
        ring: '#db2777',
        'chart-1': '#d926a2',
        'chart-2': '#6c12b9',
        'chart-3': '#274754',
        'chart-4': '#e8c468',
        'chart-5': '#f4a462',
        sidebar: '#f3e4f6',
        'sidebar-foreground': '#ac1668',
        'sidebar-primary': '#454554',
        'sidebar-primary-foreground': '#faf1f7',
        'sidebar-accent': '#f8f8f7',
        'sidebar-accent-foreground': '#454554',
        'sidebar-border': '#eceae9',
        'sidebar-ring': '#db2777',
      }),
      dark: convertTweakcnToVritti({
        background: '#221d27',
        foreground: '#d2c4de',
        card: '#2c2632',
        'card-foreground': '#dbc5d2',
        popover: '#100a0e',
        'popover-foreground': '#f8f1f5',
        primary: '#a3004c',
        'primary-foreground': '#efc0d8',
        secondary: '#362d3d',
        'secondary-foreground': '#d4c7e1',
        muted: '#28222d',
        'muted-foreground': '#c2b6cf',
        accent: '#463753',
        'accent-foreground': '#f8f1f5',
        destructive: '#301015',
        'destructive-foreground': '#ffffff',
        border: '#3b3237',
        input: '#3e343c',
        ring: '#db2777',
        'chart-1': '#a84370',
        'chart-2': '#934dcb',
        'chart-3': '#e88c30',
        'chart-4': '#af57db',
        'chart-5': '#e23670',
        sidebar: '#181117',
        'sidebar-foreground': '#e0cad6',
        'sidebar-primary': '#1d4ed8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#261922',
        'sidebar-accent-foreground': '#f4f4f5',
        'sidebar-border': '#000000',
        'sidebar-ring': '#db2777',
      }),
      radius: '0.5rem',
    },
  },
  {
    name: 'twitter',
    label: 'Twitter',
    createdAt: '2025-04-24',
    config: {
      light: convertTweakcnToVritti({
        background: '#ffffff',
        foreground: '#0f1419',
        card: '#f7f8f8',
        'card-foreground': '#0f1419',
        popover: '#ffffff',
        'popover-foreground': '#0f1419',
        primary: '#1e9df1',
        'primary-foreground': '#ffffff',
        secondary: '#0f1419',
        'secondary-foreground': '#ffffff',
        muted: '#E5E5E6',
        'muted-foreground': '#0f1419',
        accent: '#E3ECF6',
        'accent-foreground': '#1e9df1',
        destructive: '#f4212e',
        'destructive-foreground': '#ffffff',
        border: '#e1eaef',
        input: '#f7f9fa',
        ring: '#1da1f2',
        'chart-1': '#1e9df1',
        'chart-2': '#00b87a',
        'chart-3': '#f7b928',
        'chart-4': '#17bf63',
        'chart-5': '#e0245e',
        sidebar: '#f7f8f8',
        'sidebar-foreground': '#0f1419',
        'sidebar-primary': '#1e9df1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#E3ECF6',
        'sidebar-accent-foreground': '#1e9df1',
        'sidebar-border': '#e1e8ed',
        'sidebar-ring': '#1da1f2',
      }),
      dark: convertTweakcnToVritti({
        background: '#000000',
        foreground: '#e7e9ea',
        card: '#17181c',
        'card-foreground': '#d9d9d9',
        popover: '#000000',
        'popover-foreground': '#e7e9ea',
        primary: '#1c9cf0',
        'primary-foreground': '#ffffff',
        secondary: '#f0f3f4',
        'secondary-foreground': '#0f1419',
        muted: '#181818',
        'muted-foreground': '#72767a',
        accent: '#061622',
        'accent-foreground': '#1c9cf0',
        destructive: '#f4212e',
        'destructive-foreground': '#ffffff',
        border: '#242628',
        input: '#22303c',
        ring: '#1da1f2',
        'chart-1': '#1e9df1',
        'chart-2': '#00b87a',
        'chart-3': '#f7b928',
        'chart-4': '#17bf63',
        'chart-5': '#e0245e',
        sidebar: '#17181c',
        'sidebar-foreground': '#d9d9d9',
        'sidebar-primary': '#1da1f2',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#061622',
        'sidebar-accent-foreground': '#1c9cf0',
        'sidebar-border': '#38444d',
        'sidebar-ring': '#1da1f2',
      }),
      radius: '1.3rem',
    },
    fonts: {
      sans: 'Open Sans, sans-serif',
      serif: 'Georgia, serif',
      mono: 'Menlo, monospace',
    },
    shadow: {
      color: 'rgba(29,161,242,0.15)',
      opacity: '0',
      blur: '0px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '2px',
    },
  },
  {
    name: 'mocha-mousse',
    label: 'Mocha Mousse',
    createdAt: '2025-04-24',
    config: {
      light: convertTweakcnToVritti({
        background: '#F1F0E5',
        foreground: '#56453F',
        card: '#F1F0E5',
        'card-foreground': '#56453F',
        popover: '#FFFFFF',
        'popover-foreground': '#56453F',
        primary: '#A37764',
        'primary-foreground': '#FFFFFF',
        secondary: '#BAAB92',
        'secondary-foreground': '#ffffff',
        muted: '#E4C7B8',
        'muted-foreground': '#8A655A',
        accent: '#E4C7B8',
        'accent-foreground': '#56453F',
        destructive: '#1f1a17',
        'destructive-foreground': '#FFFFFF',
        border: '#BAAB92',
        input: '#BAAB92',
        ring: '#A37764',
        'chart-1': '#A37764',
        'chart-2': '#8A655A',
        'chart-3': '#C39E88',
        'chart-4': '#BAAB92',
        'chart-5': '#A28777',
        sidebar: '#ebd6cb',
        'sidebar-foreground': '#56453F',
        'sidebar-primary': '#A37764',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#C39E88',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#A28777',
        'sidebar-ring': '#A37764',
      }),
      dark: convertTweakcnToVritti({
        background: '#2d2521',
        foreground: '#F1F0E5',
        card: '#3c332e',
        'card-foreground': '#F1F0E5',
        popover: '#3c332e',
        'popover-foreground': '#F1F0E5',
        primary: '#C39E88',
        'primary-foreground': '#2d2521',
        secondary: '#5c4f47',
        'secondary-foreground': '#ffffff',
        muted: '#49403a',
        'muted-foreground': '#BAAB92',
        accent: '#49403a',
        'accent-foreground': '#E4C7B8',
        destructive: '#ef4444',
        'destructive-foreground': '#FFFFFF',
        border: '#5c4f47',
        input: '#5c4f47',
        ring: '#C39E88',
        'chart-1': '#C39E88',
        'chart-2': '#BAAB92',
        'chart-3': '#A37764',
        'chart-4': '#8A655A',
        'chart-5': '#E4C7B8',
        sidebar: '#241f1c',
        'sidebar-foreground': '#F1F0E5',
        'sidebar-primary': '#C39E88',
        'sidebar-primary-foreground': '#2d2521',
        'sidebar-accent': '#49403a',
        'sidebar-accent-foreground': '#E4C7B8',
        'sidebar-border': '#5c4f47',
        'sidebar-ring': '#C39E88',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'DM Sans, sans-serif',
      serif: 'Georgia, serif',
      mono: 'Menlo, monospace',
    },
    shadow: {
      color: 'hsl(20 18% 51% / 0.4)',
      opacity: '0.11',
      blur: '0px',
      spread: '0px',
      offsetX: '2px',
      offsetY: '2px',
    },
  },
  {
    name: 'amethyst-haze',
    label: 'Amethyst Haze',
    createdAt: '2025-05-08',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#e6a5b8',
        'accent-foreground': '#4b2e36',
        'background': '#f8f7fa',
        'border': '#cec9d9',
        'card': '#ffffff',
        'card-foreground': '#3d3c4f',
        'chart-1': '#8a79ab',
        'chart-2': '#e6a5b8',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        'destructive': '#d95c5c',
        'destructive-foreground': '#f8f7fa',
        'foreground': '#3d3c4f',
        'input': '#eae7f0',
        'muted': '#dcd9e3',
        'muted-foreground': '#6b6880',
        'popover': '#ffffff',
        'popover-foreground': '#3d3c4f',
        'primary': '#8a79ab',
        'primary-foreground': '#f8f7fa',
        'ring': '#8a79ab',
        'secondary': '#dfd9ec',
        'secondary-foreground': '#3d3c4f',
        sidebar: '#f1eff5',
        'sidebar-accent': '#e6a5b8',
        'sidebar-accent-foreground': '#4b2e36',
        'sidebar-border': '#d7d2e0',
        'sidebar-foreground': '#3d3c4f',
        'sidebar-primary': '#8a79ab',
        'sidebar-primary-foreground': '#f8f7fa',
        'sidebar-ring': '#8a79ab',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#372e3f',
        'accent-foreground': '#f2b8c6',
        'background': '#1a1823',
        'border': '#302c40',
        'card': '#232030',
        'card-foreground': '#e0ddef',
        'chart-1': '#a995c9',
        'chart-2': '#f2b8c6',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        'destructive': '#e57373',
        'destructive-foreground': '#1a1823',
        'foreground': '#e0ddef',
        'input': '#2a273a',
        'muted': '#242031',
        'muted-foreground': '#a09aad',
        'popover': '#232030',
        'popover-foreground': '#e0ddef',
        'primary': '#a995c9',
        'primary-foreground': '#1a1823',
        'ring': '#a995c9',
        'secondary': '#5a5370',
        'secondary-foreground': '#e0ddef',
        sidebar: '#16141e',
        'sidebar-accent': '#372e3f',
        'sidebar-accent-foreground': '#f2b8c6',
        'sidebar-border': '#2a273a',
        'sidebar-foreground': '#e0ddef',
        'sidebar-primary': '#a995c9',
        'sidebar-primary-foreground': '#1a1823',
        'sidebar-ring': '#a995c9',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Geist, sans-serif',
      serif: '\"Lora\", Georgia, serif',
      mono: '\"Fira Code\", \"Courier New\", monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.06',
      blur: '5px',
      spread: '1px',
      offsetX: '1px',
      offsetY: '2px',
    },
    letterSpacing: '0em',
    spacing: '0.25rem',
  },
  {
    name: 'doom-64',
    label: 'Doom 64',
    createdAt: '2025-04-28',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#4682b4',
        'accent-foreground': '#ffffff',
        'background': '#cccccc',
        'border': '#505050',
        'card': '#b0b0b0',
        'card-foreground': '#1f1f1f',
        'chart-1': '#b71c1c',
        'chart-2': '#556b2f',
        'chart-3': '#4682b4',
        'chart-4': '#ff6f00',
        'chart-5': '#8d6e63',
        'destructive': '#ff6f00',
        'destructive-foreground': '#000000',
        'foreground': '#1f1f1f',
        'input': '#505050',
        'muted': '#b8b8b8',
        'muted-foreground': '#4a4a4a',
        'popover': '#b0b0b0',
        'popover-foreground': '#1f1f1f',
        'primary': '#b71c1c',
        'primary-foreground': '#ffffff',
        'ring': '#b71c1c',
        'secondary': '#556b2f',
        'secondary-foreground': '#ffffff',
        sidebar: '#b0b0b0',
        'sidebar-accent': '#4682b4',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#505050',
        'sidebar-foreground': '#1f1f1f',
        'sidebar-primary': '#b71c1c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#b71c1c',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#64b5f6',
        'accent-foreground': '#000000',
        'background': '#1a1a1a',
        'border': '#4a4a4a',
        'card': '#2a2a2a',
        'card-foreground': '#e0e0e0',
        'chart-1': '#e53935',
        'chart-2': '#689f38',
        'chart-3': '#64b5f6',
        'chart-4': '#ffa000',
        'chart-5': '#a1887f',
        'destructive': '#ffa000',
        'destructive-foreground': '#000000',
        'foreground': '#e0e0e0',
        'input': '#4a4a4a',
        'muted': '#252525',
        'muted-foreground': '#a0a0a0',
        'popover': '#2a2a2a',
        'popover-foreground': '#e0e0e0',
        'primary': '#e53935',
        'primary-foreground': '#ffffff',
        'ring': '#e53935',
        'secondary': '#689f38',
        'secondary-foreground': '#000000',
        sidebar: '#141414',
        'sidebar-accent': '#64b5f6',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#4a4a4a',
        'sidebar-foreground': '#e0e0e0',
        'sidebar-primary': '#e53935',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#e53935',
      }),
      radius: '0px',
    },
    fonts: {
      sans: '\"Oxanium\", sans-serif',
      serif: 'ui-serif, Georgia, Cambria, ',
      mono: '\"Source Code Pro\", monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.4',
      blur: '4px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '2px',
    },
    letterSpacing: '0em',
    spacing: '0.25rem',
  },
  {
    name: 'kodama-grove',
    label: 'Kodama Grove',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#dbc894',
        'accent-foreground': '#5c4b3e',
        'background': '#e4d7b0',
        'border': '#b19681',
        'card': '#e7dbbf',
        'card-foreground': '#5c4b3e',
        'chart-1': '#9db18c',
        'chart-2': '#8a9f7b',
        'chart-3': '#bac9b4',
        'chart-4': '#71856a',
        'chart-5': '#5e6e58',
        'destructive': '#d98b7e',
        'destructive-foreground': '#faf8f2',
        'foreground': '#5c4b3e',
        'input': '#dbc894',
        'muted': '#decea0',
        'muted-foreground': '#85766a',
        'popover': '#f3ead2',
        'popover-foreground': '#5c4b3e',
        'primary': '#8d9d4f',
        'primary-foreground': '#fdfbf6',
        'ring': '#9db18c',
        'secondary': '#decea0',
        'secondary-foreground': '#5c4b3e',
        sidebar: '#e2d1a2',
        'sidebar-accent': '#eae5d9',
        'sidebar-accent-foreground': '#5c4b3e',
        'sidebar-border': '#e5e0d4',
        'sidebar-foreground': '#5c4b3e',
        'sidebar-primary': '#9db18c',
        'sidebar-primary-foreground': '#fdfbf6',
        'sidebar-ring': '#9db18c',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#a18f5c',
        'accent-foreground': '#2a2521',
        'background': '#3a3529',
        'border': '#5a5345',
        'card': '#413c33',
        'card-foreground': '#ede4d4',
        'chart-1': '#8a9f7b',
        'chart-2': '#9db18c',
        'chart-3': '#71856a',
        'chart-4': '#a18f5c',
        'chart-5': '#5e6e58',
        'destructive': '#b5766a',
        'destructive-foreground': '#f0e9db',
        'foreground': '#ede4d4',
        'input': '#5a5345',
        'muted': '#4a4439',
        'muted-foreground': '#a8a096',
        'popover': '#413c33',
        'popover-foreground': '#ede4d4',
        'primary': '#8a9f7b',
        'primary-foreground': '#2a2521',
        'ring': '#8a9f7b',
        'secondary': '#5a5345',
        'secondary-foreground': '#ede4d4',
        sidebar: '#3a3529',
        'sidebar-accent': '#a18f5c',
        'sidebar-accent-foreground': '#2a2521',
        'sidebar-border': '#5a5345',
        'sidebar-foreground': '#ede4d4',
        'sidebar-primary': '#8a9f7b',
        'sidebar-primary-foreground': '#2a2521',
        'sidebar-ring': '#8a9f7b',
      }),
      radius: '0.425rem',
    },
    fonts: {
      sans: 'Merriweather, serif',
      serif: 'Source Serif 4, serif',
      mono: 'JetBrains Mono, monospace',
    },
    shadow: {
      color: 'hsl(88 22% 35% / 0.15)',
      opacity: '0.15',
      blur: '2px',
      spread: '0px',
      offsetX: '3px',
      offsetY: '3px',
    },
  },
  {
    name: 'cosmic-night',
    label: 'Cosmic Night',
    createdAt: '2025-04-04',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#d8e6ff',
        'accent-foreground': '#2a2a4a',
        'background': '#f5f5ff',
        'border': '#e0e0f0',
        'card': '#ffffff',
        'card-foreground': '#2a2a4a',
        'chart-1': '#6e56cf',
        'chart-2': '#9e8cfc',
        'chart-3': '#5d5fef',
        'chart-4': '#7c75fa',
        'chart-5': '#4740b3',
        'destructive': '#ff5470',
        'destructive-foreground': '#ffffff',
        'foreground': '#2a2a4a',
        'input': '#e0e0f0',
        'muted': '#f0f0fa',
        'muted-foreground': '#6c6c8a',
        'popover': '#ffffff',
        'popover-foreground': '#2a2a4a',
        'primary': '#6e56cf',
        'primary-foreground': '#ffffff',
        'ring': '#6e56cf',
        'secondary': '#e4dfff',
        'secondary-foreground': '#4a4080',
        sidebar: '#f0f0fa',
        'sidebar-accent': '#d8e6ff',
        'sidebar-accent-foreground': '#2a2a4a',
        'sidebar-border': '#e0e0f0',
        'sidebar-foreground': '#2a2a4a',
        'sidebar-primary': '#6e56cf',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#6e56cf',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#303060',
        'accent-foreground': '#e2e2f5',
        'background': '#0f0f1a',
        'border': '#303052',
        'card': '#1a1a2e',
        'card-foreground': '#e2e2f5',
        'chart-1': '#a48fff',
        'chart-2': '#7986cb',
        'chart-3': '#64b5f6',
        'chart-4': '#4db6ac',
        'chart-5': '#ff79c6',
        'destructive': '#ff5470',
        'destructive-foreground': '#ffffff',
        'foreground': '#e2e2f5',
        'input': '#303052',
        'muted': '#222244',
        'muted-foreground': '#a0a0c0',
        'popover': '#1a1a2e',
        'popover-foreground': '#e2e2f5',
        'primary': '#a48fff',
        'primary-foreground': '#0f0f1a',
        'ring': '#a48fff',
        'secondary': '#2d2b55',
        'secondary-foreground': '#c4c2ff',
        sidebar: '#1a1a2e',
        'sidebar-accent': '#303060',
        'sidebar-accent-foreground': '#e2e2f5',
        'sidebar-border': '#303052',
        'sidebar-foreground': '#e2e2f5',
        'sidebar-primary': '#a48fff',
        'sidebar-primary-foreground': '#0f0f1a',
        'sidebar-ring': '#a48fff',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Inter, sans-serif',
      serif: 'Georgia, serif',
      mono: 'JetBrains Mono, monospace',
    },
    shadow: {
      color: 'hsl(240 30% 25%)',
      opacity: '0.12',
      blur: '10px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '4px',
    },
  },
  {
    name: 'quantum-rose',
    label: 'Quantum Rose',
    createdAt: '2025-04-03',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#ffc1e3',
        'accent-foreground': '#91185c',
        'background': '#fff0f8',
        'border': '#ffc7e6',
        'card': '#fff7fc',
        'card-foreground': '#91185c',
        'chart-1': '#e6067a',
        'chart-2': '#c44b97',
        'chart-3': '#9969b6',
        'chart-4': '#7371bf',
        'chart-5': '#5e84ff',
        'destructive': '#d13869',
        'destructive-foreground': '#ffffff',
        'foreground': '#91185c',
        'input': '#ffd6ff',
        'muted': '#ffe3f2',
        'muted-foreground': '#c04283',
        'popover': '#fff7fc',
        'popover-foreground': '#91185c',
        'primary': '#e6067a',
        'primary-foreground': '#ffffff',
        'ring': '#e6067a',
        'secondary': '#ffd6ff',
        'secondary-foreground': '#91185c',
        sidebar: '#ffedf6',
        'sidebar-accent': '#ffc1e3',
        'sidebar-accent-foreground': '#91185c',
        'sidebar-border': '#ffddf0',
        'sidebar-foreground': '#91185c',
        'sidebar-primary': '#e6067a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#e6067a',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#5a1f5d',
        'accent-foreground': '#ffb3ff',
        'background': '#1a0922',
        'border': '#4a1b5f',
        'card': '#2a1435',
        'card-foreground': '#ffb3ff',
        'chart-1': '#ff6bef',
        'chart-2': '#c359e3',
        'chart-3': '#9161ff',
        'chart-4': '#6f73e2',
        'chart-5': '#547aff',
        'destructive': '#ff2876',
        'destructive-foreground': '#f9f9f9',
        'foreground': '#ffb3ff',
        'input': '#46204f',
        'muted': '#331941',
        'muted-foreground': '#d67ad6',
        'popover': '#2a1435',
        'popover-foreground': '#ffb3ff',
        'primary': '#ff6bef',
        'primary-foreground': '#180518',
        'ring': '#ff6bef',
        'secondary': '#46204f',
        'secondary-foreground': '#ffb3ff',
        sidebar: '#1c0d25',
        'sidebar-accent': '#5a1f5d',
        'sidebar-accent-foreground': '#ffb3ff',
        'sidebar-border': '#4a1b5f',
        'sidebar-foreground': '#ffb3ff',
        'sidebar-primary': '#ff6bef',
        'sidebar-primary-foreground': '#180518',
        'sidebar-ring': '#ff6bef',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Poppins, sans-serif',
      serif: 'Playfair Display, serif',
      mono: 'Space Mono, monospace',
    },
    shadow: {
      color: 'hsl(330 70% 30% / 0.12)',
      opacity: '0.18',
      blur: '0px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '3px',
    },
  },
  {
    name: 'bold-tech',
    label: 'Bold Tech',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#dbeafe',
        'accent-foreground': '#1e40af',
        'background': '#ffffff',
        'border': '#e0e7ff',
        'card': '#ffffff',
        'card-foreground': '#312e81',
        'chart-1': '#8b5cf6',
        'chart-2': '#7c3aed',
        'chart-3': '#6d28d9',
        'chart-4': '#5b21b6',
        'chart-5': '#4c1d95',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#312e81',
        'input': '#e0e7ff',
        'muted': '#f5f3ff',
        'muted-foreground': '#7c3aed',
        'popover': '#ffffff',
        'popover-foreground': '#312e81',
        'primary': '#8b5cf6',
        'primary-foreground': '#ffffff',
        'ring': '#8b5cf6',
        'secondary': '#f3f0ff',
        'secondary-foreground': '#4338ca',
        sidebar: '#f5f3ff',
        'sidebar-accent': '#dbeafe',
        'sidebar-accent-foreground': '#1e40af',
        'sidebar-border': '#e0e7ff',
        'sidebar-foreground': '#312e81',
        'sidebar-primary': '#8b5cf6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#8b5cf6',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#4338ca',
        'accent-foreground': '#e0e7ff',
        'background': '#0f172a',
        'border': '#2e1065',
        'card': '#1e1b4b',
        'card-foreground': '#e0e7ff',
        'chart-1': '#a78bfa',
        'chart-2': '#8b5cf6',
        'chart-3': '#7c3aed',
        'chart-4': '#6d28d9',
        'chart-5': '#5b21b6',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#e0e7ff',
        'input': '#2e1065',
        'muted': '#171447',
        'muted-foreground': '#c4b5fd',
        'popover': '#1e1b4b',
        'popover-foreground': '#e0e7ff',
        'primary': '#8b5cf6',
        'primary-foreground': '#ffffff',
        'ring': '#8b5cf6',
        'secondary': '#1e1b4b',
        'secondary-foreground': '#e0e7ff',
        sidebar: '#0f172a',
        'sidebar-accent': '#4338ca',
        'sidebar-accent-foreground': '#e0e7ff',
        'sidebar-border': '#2e1065',
        'sidebar-foreground': '#e0e7ff',
        'sidebar-primary': '#8b5cf6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#8b5cf6',
      }),
      radius: '0.625rem',
    },
    fonts: {
      sans: 'Roboto, sans-serif',
      serif: 'Playfair Display, serif',
      mono: 'Fira Code, monospace',
    },
    shadow: {
      color: 'hsl(255 86% 66%)',
      opacity: '0.2',
      blur: '4px',
      spread: '0px',
      offsetX: '2px',
      offsetY: '2px',
    },
  },
  {
    name: 'elegant-luxury',
    label: 'Elegant Luxury',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#fef3c7',
        'accent-foreground': '#7f1d1d',
        'background': '#faf7f5',
        'border': '#f5e8d2',
        'card': '#faf7f5',
        'card-foreground': '#1a1a1a',
        'chart-1': '#b91c1c',
        'chart-2': '#9b2c2c',
        'chart-3': '#7f1d1d',
        'chart-4': '#b45309',
        'chart-5': '#92400e',
        'destructive': '#991b1b',
        'destructive-foreground': '#ffffff',
        'foreground': '#1a1a1a',
        'input': '#f5e8d2',
        'muted': '#f0ebe8',
        'muted-foreground': '#57534e',
        'popover': '#faf7f5',
        'popover-foreground': '#1a1a1a',
        'primary': '#9b2c2c',
        'primary-foreground': '#ffffff',
        'ring': '#9b2c2c',
        'secondary': '#fdf2d6',
        'secondary-foreground': '#805500',
        sidebar: '#f0ebe8',
        'sidebar-accent': '#fef3c7',
        'sidebar-accent-foreground': '#7f1d1d',
        'sidebar-border': '#f5e8d2',
        'sidebar-foreground': '#1a1a1a',
        'sidebar-primary': '#9b2c2c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#9b2c2c',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#b45309',
        'accent-foreground': '#fef3c7',
        'background': '#1c1917',
        'border': '#44403c',
        'card': '#292524',
        'card-foreground': '#f5f5f4',
        'chart-1': '#f87171',
        'chart-2': '#ef4444',
        'chart-3': '#dc2626',
        'chart-4': '#fbbf24',
        'chart-5': '#f59e0b',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#f5f5f4',
        'input': '#44403c',
        'muted': '#1f1c1a',
        'muted-foreground': '#d6d3d1',
        'popover': '#292524',
        'popover-foreground': '#f5f5f4',
        'primary': '#b91c1c',
        'primary-foreground': '#faf7f5',
        'ring': '#b91c1c',
        'secondary': '#92400e',
        'secondary-foreground': '#fef3c7',
        sidebar: '#1c1917',
        'sidebar-accent': '#b45309',
        'sidebar-accent-foreground': '#fef3c7',
        'sidebar-border': '#44403c',
        'sidebar-foreground': '#f5f5f4',
        'sidebar-primary': '#b91c1c',
        'sidebar-primary-foreground': '#faf7f5',
        'sidebar-ring': '#b91c1c',
      }),
      radius: '0.375rem',
    },
    fonts: {
      sans: 'Poppins, sans-serif',
      serif: 'Libre Baskerville, serif',
      mono: 'IBM Plex Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 63% 18%)',
      opacity: '0.12',
      blur: '16px',
      spread: '-2px',
      offsetX: '1px',
      offsetY: '1px',
    },
  },
  {
    name: 'amber-minimal',
    label: 'Amber Minimal',
    createdAt: '2025-04-27',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#fffbeb',
        'accent-foreground': '#92400e',
        'background': '#ffffff',
        'border': '#e5e7eb',
        'card': '#ffffff',
        'card-foreground': '#262626',
        'chart-1': '#f59e0b',
        'chart-2': '#d97706',
        'chart-3': '#b45309',
        'chart-4': '#92400e',
        'chart-5': '#78350f',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#262626',
        'input': '#e5e7eb',
        'muted': '#f9fafb',
        'muted-foreground': '#6b7280',
        'popover': '#ffffff',
        'popover-foreground': '#262626',
        'primary': '#f59e0b',
        'primary-foreground': '#000000',
        'ring': '#f59e0b',
        'secondary': '#f3f4f6',
        'secondary-foreground': '#4b5563',
        sidebar: '#f9fafb',
        'sidebar-accent': '#fffbeb',
        'sidebar-accent-foreground': '#92400e',
        'sidebar-border': '#e5e7eb',
        'sidebar-foreground': '#262626',
        'sidebar-primary': '#f59e0b',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#f59e0b',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#92400e',
        'accent-foreground': '#fde68a',
        'background': '#171717',
        'border': '#404040',
        'card': '#262626',
        'card-foreground': '#e5e5e5',
        'chart-1': '#fbbf24',
        'chart-2': '#d97706',
        'chart-3': '#92400e',
        'chart-4': '#b45309',
        'chart-5': '#92400e',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#e5e5e5',
        'input': '#404040',
        'muted': '#1f1f1f',
        'muted-foreground': '#a3a3a3',
        'popover': '#262626',
        'popover-foreground': '#e5e5e5',
        'primary': '#f59e0b',
        'primary-foreground': '#000000',
        'ring': '#f59e0b',
        'secondary': '#262626',
        'secondary-foreground': '#e5e5e5',
        sidebar: '#0f0f0f',
        'sidebar-accent': '#92400e',
        'sidebar-accent-foreground': '#fde68a',
        'sidebar-border': '#404040',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#f59e0b',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#f59e0b',
      }),
      radius: '0.375rem',
    },
    fonts: {
      sans: 'Inter, sans-serif',
      serif: 'Source Serif 4, serif',
      mono: 'JetBrains Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.1',
      blur: '8px',
      spread: '-1px',
      offsetX: '0px',
      offsetY: '4px',
    },
    letterSpacing: '0em',
    spacing: '0.25rem',
  },
  {
    name: 'neo-brutalism',
    label: 'Neo Brutalism',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#0066ff',
        'accent-foreground': '#ffffff',
        'background': '#ffffff',
        'border': '#000000',
        'card': '#ffffff',
        'card-foreground': '#000000',
        'chart-1': '#ff3333',
        'chart-2': '#ffff00',
        'chart-3': '#0066ff',
        'chart-4': '#00cc00',
        'chart-5': '#cc00cc',
        'destructive': '#000000',
        'destructive-foreground': '#ffffff',
        'foreground': '#000000',
        'input': '#000000',
        'muted': '#f0f0f0',
        'muted-foreground': '#333333',
        'popover': '#ffffff',
        'popover-foreground': '#000000',
        'primary': '#ff3333',
        'primary-foreground': '#ffffff',
        'ring': '#ff3333',
        'secondary': '#ffff00',
        'secondary-foreground': '#000000',
        sidebar: '#f0f0f0',
        'sidebar-accent': '#0066ff',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#000000',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#ff3333',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#ff3333',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#3399ff',
        'accent-foreground': '#000000',
        'background': '#000000',
        'border': '#ffffff',
        'card': '#333333',
        'card-foreground': '#ffffff',
        'chart-1': '#ff6666',
        'chart-2': '#ffff33',
        'chart-3': '#3399ff',
        'chart-4': '#33cc33',
        'chart-5': '#cc33cc',
        'destructive': '#ffffff',
        'destructive-foreground': '#000000',
        'foreground': '#ffffff',
        'input': '#ffffff',
        'muted': '#1a1a1a',
        'muted-foreground': '#cccccc',
        'popover': '#333333',
        'popover-foreground': '#ffffff',
        'primary': '#ff6666',
        'primary-foreground': '#000000',
        'ring': '#ff6666',
        'secondary': '#ffff33',
        'secondary-foreground': '#000000',
        sidebar: '#000000',
        'sidebar-accent': '#3399ff',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ffffff',
        'sidebar-foreground': '#ffffff',
        'sidebar-primary': '#ff6666',
        'sidebar-primary-foreground': '#000000',
        'sidebar-ring': '#ff6666',
      }),
      radius: '0px',
    },
    fonts: {
      sans: 'DM Sans, sans-serif',
      mono: 'Space Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '1',
      blur: '0px',
      spread: '0px',
      offsetX: '4px',
      offsetY: '4px',
    },
  },
  {
    name: 'solar-dusk',
    label: 'Solar Dusk',
    createdAt: '2025-04-12',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#f2daba',
        'accent-foreground': '#57534E',
        'background': '#FDFBF7',
        'border': '#E4D9BC',
        'card': '#F8F4EE',
        'card-foreground': '#4A3B33',
        'chart-1': '#B45309',
        'chart-2': '#78716C',
        'chart-3': '#A16207',
        'chart-4': '#78716C',
        'chart-5': '#CA8A04',
        'destructive': '#991B1B',
        'destructive-foreground': '#FFFFFF',
        'foreground': '#4A3B33',
        'input': '#E4D9BC',
        'muted': '#F1E9DA',
        'muted-foreground': '#78716C',
        'popover': '#F8F4EE',
        'popover-foreground': '#4A3B33',
        'primary': '#B45309',
        'primary-foreground': '#FFFFFF',
        'ring': '#B45309',
        'secondary': '#E4C090',
        'secondary-foreground': '#57534E',
        sidebar: '#F1E9DA',
        'sidebar-accent': '#A16207',
        'sidebar-accent-foreground': '#FFFFFF',
        'sidebar-border': '#E4D9BC',
        'sidebar-foreground': '#4A3B33',
        'sidebar-primary': '#B45309',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-ring': '#B45309',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#1e4252',
        'accent-foreground': '#E7E5E4',
        'background': '#1C1917',
        'border': '#44403C',
        'card': '#292524',
        'card-foreground': '#F5F5F4',
        'chart-1': '#F97316',
        'chart-2': '#0EA5E9',
        'chart-3': '#EAB308',
        'chart-4': '#A8A29E',
        'chart-5': '#78716C',
        'destructive': '#DC2626',
        'destructive-foreground': '#FFFFFF',
        'foreground': '#F5F5F4',
        'input': '#44403C',
        'muted': '#201d1a',
        'muted-foreground': '#A8A29E',
        'popover': '#292524',
        'popover-foreground': '#F5F5F4',
        'primary': '#F97316',
        'primary-foreground': '#FFFFFF',
        'ring': '#F97316',
        'secondary': '#57534E',
        'secondary-foreground': '#E7E5E4',
        sidebar: '#292524',
        'sidebar-accent': '#0EA5E9',
        'sidebar-accent-foreground': '#0C2A4D',
        'sidebar-border': '#44403C',
        'sidebar-foreground': '#F5F5F4',
        'sidebar-primary': '#F97316',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-ring': '#F97316',
      }),
      radius: '0.3rem',
    },
    fonts: {
      sans: 'Oxanium, sans-serif',
      serif: 'Merriweather, serif',
      mono: 'Fira Code, monospace',
    },
    shadow: {
      color: 'hsl(28 18% 25%)',
      opacity: '0.18',
      blur: '3px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '2px',
    },
  },
  {
    name: 'pastel-dreams',
    label: 'Pastel Dreams',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#f3e5f5',
        'accent-foreground': '#374151',
        'background': '#f7f3f9',
        'border': '#e9d8fd',
        'card': '#ffffff',
        'card-foreground': '#374151',
        'chart-1': '#a78bfa',
        'chart-2': '#8b5cf6',
        'chart-3': '#7c3aed',
        'chart-4': '#6d28d9',
        'chart-5': '#5b21b6',
        'destructive': '#fca5a5',
        'destructive-foreground': '#ffffff',
        'foreground': '#374151',
        'input': '#e9d8fd',
        'muted': '#f3e8ff',
        'muted-foreground': '#6b7280',
        'popover': '#ffffff',
        'popover-foreground': '#374151',
        'primary': '#a78bfa',
        'primary-foreground': '#ffffff',
        'ring': '#a78bfa',
        'secondary': '#e9d8fd',
        'secondary-foreground': '#4b5563',
        sidebar: '#e9d8fd',
        'sidebar-accent': '#f3e5f5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#e9d8fd',
        'sidebar-foreground': '#374151',
        'sidebar-primary': '#a78bfa',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#a78bfa',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#4a3d5a',
        'accent-foreground': '#d1d5db',
        'background': '#1c1917',
        'border': '#3f324a',
        'card': '#2d2535',
        'card-foreground': '#e0e7ff',
        'chart-1': '#c0aafd',
        'chart-2': '#a78bfa',
        'chart-3': '#8b5cf6',
        'chart-4': '#7c3aed',
        'chart-5': '#6d28d9',
        'destructive': '#fca5a5',
        'destructive-foreground': '#1c1917',
        'foreground': '#e0e7ff',
        'input': '#3f324a',
        'muted': '#20182b',
        'muted-foreground': '#9ca3af',
        'popover': '#2d2535',
        'popover-foreground': '#e0e7ff',
        'primary': '#c0aafd',
        'primary-foreground': '#1c1917',
        'ring': '#c0aafd',
        'secondary': '#3f324a',
        'secondary-foreground': '#d1d5db',
        sidebar: '#3f324a',
        'sidebar-accent': '#4a3d5a',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#3f324a',
        'sidebar-foreground': '#e0e7ff',
        'sidebar-primary': '#c0aafd',
        'sidebar-primary-foreground': '#1c1917',
        'sidebar-ring': '#c0aafd',
      }),
      radius: '1.5rem',
    },
    fonts: {
      sans: 'Open Sans, sans-serif',
      serif: 'Source Serif 4, serif',
      mono: 'IBM Plex Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.08',
      blur: '16px',
      spread: '-4px',
      offsetX: '0px',
      offsetY: '8px',
    },
  },
  {
    name: 'clean-slate',
    label: 'Clean Slate',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#e0e7ff',
        'accent-foreground': '#374151',
        'background': '#f8fafc',
        'border': '#d1d5db',
        'card': '#ffffff',
        'card-foreground': '#1e293b',
        'chart-1': '#6366f1',
        'chart-2': '#4f46e5',
        'chart-3': '#4338ca',
        'chart-4': '#3730a3',
        'chart-5': '#312e81',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#1e293b',
        'input': '#d1d5db',
        'muted': '#f3f4f6',
        'muted-foreground': '#6b7280',
        'popover': '#ffffff',
        'popover-foreground': '#1e293b',
        'primary': '#6366f1',
        'primary-foreground': '#ffffff',
        'ring': '#6366f1',
        'secondary': '#e5e7eb',
        'secondary-foreground': '#374151',
        sidebar: '#f3f4f6',
        'sidebar-accent': '#e0e7ff',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#d1d5db',
        'sidebar-foreground': '#1e293b',
        'sidebar-primary': '#6366f1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#6366f1',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#374151',
        'accent-foreground': '#d1d5db',
        'background': '#0f172a',
        'border': '#4b5563',
        'card': '#1e293b',
        'card-foreground': '#e2e8f0',
        'chart-1': '#818cf8',
        'chart-2': '#6366f1',
        'chart-3': '#4f46e5',
        'chart-4': '#4338ca',
        'chart-5': '#3730a3',
        'destructive': '#ef4444',
        'destructive-foreground': '#0f172a',
        'foreground': '#e2e8f0',
        'input': '#4b5563',
        'muted': '#152032',
        'muted-foreground': '#9ca3af',
        'popover': '#1e293b',
        'popover-foreground': '#e2e8f0',
        'primary': '#818cf8',
        'primary-foreground': '#0f172a',
        'ring': '#818cf8',
        'secondary': '#2d3748',
        'secondary-foreground': '#d1d5db',
        sidebar: '#1e293b',
        'sidebar-accent': '#374151',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#4b5563',
        'sidebar-foreground': '#e2e8f0',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-ring': '#818cf8',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Inter, sans-serif',
      serif: 'Merriweather, serif',
      mono: 'JetBrains Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.1',
      blur: '8px',
      spread: '-1px',
      offsetX: '0px',
      offsetY: '4px',
    },
  },
  {
    name: 'ocean-breeze',
    label: 'Ocean Breeze',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#d1fae5',
        'accent-foreground': '#374151',
        'background': '#f0f8ff',
        'border': '#e5e7eb',
        'card': '#ffffff',
        'card-foreground': '#374151',
        'chart-1': '#22c55e',
        'chart-2': '#10b981',
        'chart-3': '#059669',
        'chart-4': '#047857',
        'chart-5': '#065f46',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#374151',
        'input': '#e5e7eb',
        'muted': '#f3f4f6',
        'muted-foreground': '#6b7280',
        'popover': '#ffffff',
        'popover-foreground': '#374151',
        'primary': '#22c55e',
        'primary-foreground': '#ffffff',
        'ring': '#22c55e',
        'secondary': '#e0f2fe',
        'secondary-foreground': '#4b5563',
        sidebar: '#e0f2fe',
        'sidebar-accent': '#d1fae5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#e5e7eb',
        'sidebar-foreground': '#374151',
        'sidebar-primary': '#22c55e',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#22c55e',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#374151',
        'accent-foreground': '#a1a1aa',
        'background': '#0f172a',
        'border': '#4b5563',
        'card': '#1e293b',
        'card-foreground': '#d1d5db',
        'chart-1': '#34d399',
        'chart-2': '#2dd4bf',
        'chart-3': '#22c55e',
        'chart-4': '#10b981',
        'chart-5': '#059669',
        'destructive': '#ef4444',
        'destructive-foreground': '#0f172a',
        'foreground': '#d1d5db',
        'input': '#4b5563',
        'muted': '#19212e',
        'muted-foreground': '#6b7280',
        'popover': '#1e293b',
        'popover-foreground': '#d1d5db',
        'primary': '#34d399',
        'primary-foreground': '#0f172a',
        'ring': '#34d399',
        'secondary': '#2d3748',
        'secondary-foreground': '#a1a1aa',
        sidebar: '#1e293b',
        'sidebar-accent': '#374151',
        'sidebar-accent-foreground': '#a1a1aa',
        'sidebar-border': '#4b5563',
        'sidebar-foreground': '#d1d5db',
        'sidebar-primary': '#34d399',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-ring': '#34d399',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'DM Sans, sans-serif',
      serif: 'Lora, serif',
      mono: 'IBM Plex Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.1',
      blur: '8px',
      spread: '-1px',
      offsetX: '0px',
      offsetY: '4px',
    },
  },
  {
    name: 'retro-arcade',
    label: 'Retro Arcade',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#cb4b16',
        'accent-foreground': '#ffffff',
        'background': '#fdf6e3',
        'border': '#839496',
        'card': '#eee8d5',
        'card-foreground': '#073642',
        'chart-1': '#268bd2',
        'chart-2': '#2aa198',
        'chart-3': '#d33682',
        'chart-4': '#cb4b16',
        'chart-5': '#dc322f',
        'destructive': '#dc322f',
        'destructive-foreground': '#ffffff',
        'foreground': '#073642',
        'input': '#839496',
        'muted': '#93a1a1',
        'muted-foreground': '#073642',
        'popover': '#eee8d5',
        'popover-foreground': '#073642',
        'primary': '#d33682',
        'primary-foreground': '#ffffff',
        'ring': '#d33682',
        'secondary': '#2aa198',
        'secondary-foreground': '#ffffff',
        sidebar: '#fdf6e3',
        'sidebar-accent': '#2aa198',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#839496',
        'sidebar-foreground': '#073642',
        'sidebar-primary': '#d33682',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#d33682',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#cb4b16',
        'accent-foreground': '#ffffff',
        'background': '#002b36',
        'border': '#586e75',
        'card': '#073642',
        'card-foreground': '#93a1a1',
        'chart-1': '#268bd2',
        'chart-2': '#2aa198',
        'chart-3': '#d33682',
        'chart-4': '#cb4b16',
        'chart-5': '#dc322f',
        'destructive': '#dc322f',
        'destructive-foreground': '#ffffff',
        'foreground': '#93a1a1',
        'input': '#586e75',
        'muted': '#586e75',
        'muted-foreground': '#93a1a1',
        'popover': '#073642',
        'popover-foreground': '#93a1a1',
        'primary': '#d33682',
        'primary-foreground': '#ffffff',
        'ring': '#d33682',
        'secondary': '#2aa198',
        'secondary-foreground': '#ffffff',
        sidebar: '#002b36',
        'sidebar-accent': '#2aa198',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#586e75',
        'sidebar-foreground': '#93a1a1',
        'sidebar-primary': '#d33682',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#d33682',
      }),
      radius: '0.25rem',
    },
    fonts: {
      sans: 'Outfit, sans-serif',
      mono: 'Space Mono, monospace',
    },
    shadow: {
      color: 'hsl(196 83% 10%)',
      opacity: '0.15',
      blur: '4px',
      spread: '0px',
      offsetX: '2px',
      offsetY: '2px',
    },
  },
  {
    name: 'midnight-bloom',
    label: 'Midnight Bloom',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#8b9467',
        'accent-foreground': '#ffffff',
        'background': '#f9f9f9',
        'border': '#d4d4d4',
        'card': '#ffffff',
        'card-foreground': '#333333',
        'chart-1': '#6c5ce7',
        'chart-2': '#8e44ad',
        'chart-3': '#4b0082',
        'chart-4': '#6495ed',
        'chart-5': '#4682b4',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#333333',
        'input': '#d4d4d4',
        'muted': '#c9c4b5',
        'muted-foreground': '#6e6e6e',
        'popover': '#ffffff',
        'popover-foreground': '#333333',
        'primary': '#6c5ce7',
        'primary-foreground': '#ffffff',
        'ring': '#6c5ce7',
        'secondary': '#a1c9f2',
        'secondary-foreground': '#333333',
        sidebar: '#f9f9f9',
        'sidebar-accent': '#8b9467',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#d4d4d4',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#6c5ce7',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#6c5ce7',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#6495ed',
        'accent-foreground': '#e5e5e5',
        'background': '#1a1d23',
        'border': '#444444',
        'card': '#2f3436',
        'card-foreground': '#e5e5e5',
        'chart-1': '#6c5ce7',
        'chart-2': '#8e44ad',
        'chart-3': '#4b0082',
        'chart-4': '#6495ed',
        'chart-5': '#4682b4',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#e5e5e5',
        'input': '#444444',
        'muted': '#444444',
        'muted-foreground': '#a3a3a3',
        'popover': '#2f3436',
        'popover-foreground': '#e5e5e5',
        'primary': '#6c5ce7',
        'primary-foreground': '#ffffff',
        'ring': '#6c5ce7',
        'secondary': '#4b0082',
        'secondary-foreground': '#e5e5e5',
        sidebar: '#1a1d23',
        'sidebar-accent': '#6495ed',
        'sidebar-accent-foreground': '#e5e5e5',
        'sidebar-border': '#444444',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#6c5ce7',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#6c5ce7',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Montserrat, sans-serif',
      serif: 'Playfair Display, serif',
      mono: 'Source Code Pro, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.1',
      blur: '10px',
      spread: '-2px',
      offsetX: '0px',
      offsetY: '5px',
    },
  },
  {
    name: 'northern-lights',
    label: 'Northern Lights',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#66d9ef',
        'accent-foreground': '#333333',
        'background': '#f9f9fa',
        'border': '#d4d4d4',
        'card': '#ffffff',
        'card-foreground': '#333333',
        'chart-1': '#34a85a',
        'chart-2': '#6495ed',
        'chart-3': '#66d9ef',
        'chart-4': '#4682b4',
        'chart-5': '#1a9641',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#333333',
        'input': '#d4d4d4',
        'muted': '#ddd9c4',
        'muted-foreground': '#6e6e6e',
        'popover': '#ffffff',
        'popover-foreground': '#333333',
        'primary': '#34a85a',
        'primary-foreground': '#ffffff',
        'ring': '#34a85a',
        'secondary': '#6495ed',
        'secondary-foreground': '#ffffff',
        sidebar: '#f9f9fa',
        'sidebar-accent': '#66d9ef',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#d4d4d4',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#34a85a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#34a85a',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#6495ed',
        'accent-foreground': '#e5e5e5',
        'background': '#1a1d23',
        'border': '#444444',
        'card': '#2f3436',
        'card-foreground': '#e5e5e5',
        'chart-1': '#34a85a',
        'chart-2': '#4682b4',
        'chart-3': '#6495ed',
        'chart-4': '#66d9ef',
        'chart-5': '#1a9641',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#e5e5e5',
        'input': '#444444',
        'muted': '#444444',
        'muted-foreground': '#a3a3a3',
        'popover': '#2f3436',
        'popover-foreground': '#e5e5e5',
        'primary': '#34a85a',
        'primary-foreground': '#ffffff',
        'ring': '#34a85a',
        'secondary': '#4682b4',
        'secondary-foreground': '#e5e5e5',
        sidebar: '#1a1d23',
        'sidebar-accent': '#6495ed',
        'sidebar-accent-foreground': '#e5e5e5',
        'sidebar-border': '#444444',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#34a85a',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#34a85a',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Plus Jakarta Sans, sans-serif',
      serif: 'Source Serif 4, serif',
      mono: 'JetBrains Mono, monospace',
    },
  },
  {
    name: 'vintage-paper',
    label: 'Vintage Paper',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#d4c8aa',
        'accent-foreground': '#4a3f35',
        'background': '#f5f1e6',
        'border': '#dbd0ba',
        'card': '#fffcf5',
        'card-foreground': '#4a3f35',
        'chart-1': '#a67c52',
        'chart-2': '#8d6e4c',
        'chart-3': '#735a3a',
        'chart-4': '#b3906f',
        'chart-5': '#c0a080',
        'destructive': '#b54a35',
        'destructive-foreground': '#ffffff',
        'foreground': '#4a3f35',
        'input': '#dbd0ba',
        'muted': '#ece5d8',
        'muted-foreground': '#7d6b56',
        'popover': '#fffcf5',
        'popover-foreground': '#4a3f35',
        'primary': '#a67c52',
        'primary-foreground': '#ffffff',
        'ring': '#a67c52',
        'secondary': '#e2d8c3',
        'secondary-foreground': '#5c4d3f',
        sidebar: '#ece5d8',
        'sidebar-accent': '#d4c8aa',
        'sidebar-accent-foreground': '#4a3f35',
        'sidebar-border': '#dbd0ba',
        'sidebar-foreground': '#4a3f35',
        'sidebar-primary': '#a67c52',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#a67c52',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#59493e',
        'accent-foreground': '#ece5d8',
        'background': '#2d2621',
        'border': '#4a4039',
        'card': '#3a322c',
        'card-foreground': '#ece5d8',
        'chart-1': '#c0a080',
        'chart-2': '#b3906f',
        'chart-3': '#a67c52',
        'chart-4': '#8d6e4c',
        'chart-5': '#735a3a',
        'destructive': '#b54a35',
        'destructive-foreground': '#ffffff',
        'foreground': '#ece5d8',
        'input': '#4a4039',
        'muted': '#312b26',
        'muted-foreground': '#c5bcac',
        'popover': '#3a322c',
        'popover-foreground': '#ece5d8',
        'primary': '#c0a080',
        'primary-foreground': '#2d2621',
        'ring': '#c0a080',
        'secondary': '#4a4039',
        'secondary-foreground': '#ece5d8',
        sidebar: '#2d2621',
        'sidebar-accent': '#59493e',
        'sidebar-accent-foreground': '#ece5d8',
        'sidebar-border': '#4a4039',
        'sidebar-foreground': '#ece5d8',
        'sidebar-primary': '#c0a080',
        'sidebar-primary-foreground': '#2d2621',
        'sidebar-ring': '#c0a080',
      }),
      radius: '0.25rem',
    },
    fonts: {
      sans: 'Libre Baskerville, serif',
      serif: 'Lora, serif',
      mono: 'IBM Plex Mono, monospace',
    },
    shadow: {
      color: 'hsl(28 13% 20%)',
      opacity: '0.12',
      blur: '5px',
      spread: '0px',
      offsetX: '2px',
      offsetY: '3px',
    },
  },
  {
    name: 'sunset-horizon',
    label: 'Sunset Horizon',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#feb47b',
        'accent-foreground': '#3d3436',
        'background': '#fff9f5',
        'border': '#ffe0d6',
        'card': '#ffffff',
        'card-foreground': '#3d3436',
        'chart-1': '#ff7e5f',
        'chart-2': '#feb47b',
        'chart-3': '#ffcaa7',
        'chart-4': '#ffad8f',
        'chart-5': '#ce6a57',
        'destructive': '#e63946',
        'destructive-foreground': '#ffffff',
        'foreground': '#3d3436',
        'input': '#ffe0d6',
        'muted': '#fff0eb',
        'muted-foreground': '#78716C',
        'popover': '#ffffff',
        'popover-foreground': '#3d3436',
        'primary': '#ff7e5f',
        'primary-foreground': '#ffffff',
        'ring': '#ff7e5f',
        'secondary': '#ffedea',
        'secondary-foreground': '#b35340',
        sidebar: '#fff0eb',
        'sidebar-accent': '#feb47b',
        'sidebar-accent-foreground': '#3d3436',
        'sidebar-border': '#ffe0d6',
        'sidebar-foreground': '#3d3436',
        'sidebar-primary': '#ff7e5f',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#ff7e5f',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#feb47b',
        'accent-foreground': '#2a2024',
        'background': '#2a2024',
        'border': '#463a41',
        'card': '#392f35',
        'card-foreground': '#f2e9e4',
        'chart-1': '#ff7e5f',
        'chart-2': '#feb47b',
        'chart-3': '#ffcaa7',
        'chart-4': '#ffad8f',
        'chart-5': '#ce6a57',
        'destructive': '#e63946',
        'destructive-foreground': '#ffffff',
        'foreground': '#f2e9e4',
        'input': '#463a41',
        'muted': '#30272c',
        'muted-foreground': '#d7c6bc',
        'popover': '#392f35',
        'popover-foreground': '#f2e9e4',
        'primary': '#ff7e5f',
        'primary-foreground': '#ffffff',
        'ring': '#ff7e5f',
        'secondary': '#463a41',
        'secondary-foreground': '#f2e9e4',
        sidebar: '#2a2024',
        'sidebar-accent': '#feb47b',
        'sidebar-accent-foreground': '#2a2024',
        'sidebar-border': '#463a41',
        'sidebar-foreground': '#f2e9e4',
        'sidebar-primary': '#ff7e5f',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#ff7e5f',
      }),
      radius: '0.625rem',
    },
    fonts: {
      sans: 'Montserrat, sans-serif',
      serif: 'Merriweather, serif',
      mono: 'Ubuntu Mono, monospace',
    },
    shadow: {
      color: 'hsl(0 0% 0%)',
      opacity: '0.09',
      blur: '12px',
      spread: '-3px',
      offsetX: '0px',
      offsetY: '6px',
    },
  },
  {
    name: 'starry-night',
    label: 'Starry Night',
    createdAt: '2025-04-16',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#6ea3c1',
        'accent-foreground': '#fffbe6',
        'background': '#f5f7fa',
        'border': '#b0b8c1',
        'card': '#e3eaf2',
        'card-foreground': '#1a2238',
        'chart-1': '#3a5ba0',
        'chart-2': '#f7c873',
        'chart-3': '#6ea3c1',
        'chart-4': '#b0b8c1',
        'chart-5': '#2d1e2f',
        'destructive': '#2d1e2f',
        'destructive-foreground': '#fffbe6',
        'foreground': '#1a2238',
        'input': '#6ea3c1',
        'muted': '#e5e5df',
        'muted-foreground': '#3a5ba0',
        'popover': '#fffbe6',
        'popover-foreground': '#1a2238',
        'primary': '#3a5ba0',
        'primary-foreground': '#fffbe6',
        'ring': '#f7c873',
        'secondary': '#f7c873',
        'secondary-foreground': '#1a2238',
        sidebar: '#e3eaf2',
        'sidebar-accent': '#f7c873',
        'sidebar-accent-foreground': '#1a2238',
        'sidebar-border': '#b0b8c1',
        'sidebar-foreground': '#1a2238',
        'sidebar-primary': '#3a5ba0',
        'sidebar-primary-foreground': '#fffbe6',
        'sidebar-ring': '#f7c873',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#bccdf0',
        'accent-foreground': '#181a24',
        'background': '#181a24',
        'border': '#2d2e3e',
        'card': '#23243a',
        'card-foreground': '#e6eaf3',
        'chart-1': '#3a5ba0',
        'chart-2': '#ffe066',
        'chart-3': '#6ea3c1',
        'chart-4': '#7a88a1',
        'chart-5': '#a04a6c',
        'destructive': '#a04a6c',
        'destructive-foreground': '#ffe066',
        'foreground': '#e6eaf3',
        'input': '#3a5ba0',
        'muted': '#1d1e2f',
        'muted-foreground': '#7a88a1',
        'popover': '#23243a',
        'popover-foreground': '#ffe066',
        'primary': '#3a5ba0',
        'primary-foreground': '#ffe066',
        'ring': '#ffe066',
        'secondary': '#ffe066',
        'secondary-foreground': '#23243a',
        sidebar: '#23243a',
        'sidebar-accent': '#ffe066',
        'sidebar-accent-foreground': '#23243a',
        'sidebar-border': '#2d2e3e',
        'sidebar-foreground': '#e6eaf3',
        'sidebar-primary': '#3a5ba0',
        'sidebar-primary-foreground': '#ffe066',
        'sidebar-ring': '#ffe066',
      }),
      radius: '0.5rem',
    },
    fonts: {
      sans: 'Libre Baskerville, serif',
    },
  },
  {
    name: 'soft-pop',
    label: 'Soft Pop',
    createdAt: '2025-07-08',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#f59e0b',
        'accent-foreground': '#000000',
        'background': '#f7f9f3',
        'border': '#000000',
        'card': '#ffffff',
        'card-foreground': '#000000',
        'chart-1': '#4f46e5',
        'chart-2': '#14b8a6',
        'chart-3': '#f59e0b',
        'chart-4': '#ec4899',
        'chart-5': '#22c55e',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#000000',
        'input': '#737373',
        'muted': '#f0f0f0',
        'muted-foreground': '#333333',
        'popover': '#ffffff',
        'popover-foreground': '#000000',
        'primary': '#4f46e5',
        'primary-foreground': '#ffffff',
        'ring': '#a5b4fc',
        'secondary': '#14b8a6',
        'secondary-foreground': '#ffffff',
        sidebar: '#f7f9f3',
        'sidebar-accent': '#f59e0b',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#000000',
        'sidebar-foreground': '#000000',
        'sidebar-primary': '#4f46e5',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#a5b4fc',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#fcd34d',
        'accent-foreground': '#000000',
        'background': '#000000',
        'border': '#545454',
        'card': '#1a212b',
        'card-foreground': '#ffffff',
        'chart-1': '#818cf8',
        'chart-2': '#2dd4bf',
        'chart-3': '#fcd34d',
        'chart-4': '#f472b6',
        'chart-5': '#4ade80',
        'destructive': '#f87171',
        'destructive-foreground': '#000000',
        'foreground': '#ffffff',
        'input': '#ffffff',
        'muted': '#333333',
        'muted-foreground': '#cccccc',
        'popover': '#1a212b',
        'popover-foreground': '#ffffff',
        'primary': '#818cf8',
        'primary-foreground': '#000000',
        'ring': '#818cf8',
        'secondary': '#2dd4bf',
        'secondary-foreground': '#000000',
        sidebar: '#000000',
        'sidebar-accent': '#fcd34d',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#ffffff',
        'sidebar-foreground': '#ffffff',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#000000',
        'sidebar-ring': '#818cf8',
      }),
      radius: '1rem',
    },
    fonts: {
      sans: 'DM Sans, sans-serif',
      serif: 'DM Sans, sans-serif',
      mono: 'Space Mono, monospace',
    },
    shadow: {
      color: '#1a1a1a',
      opacity: '0.05',
      blur: '0px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '0px',
    },
    letterSpacing: 'normal',
    spacing: '0.25rem',
  },
  {
    name: 'sage-garden',
    label: 'Sage Garden',
    createdAt: '2025-11-08',
    config: {
      light: convertTweakcnToVritti({
        'accent': '#bfc9bb',
        'accent-foreground': '#1a1f2e',
        'background': '#f8f7f4',
        'border': '#e8e6e1',
        'card': '#ffffff',
        'card-foreground': '#1a1f2e',
        'chart-1': '#7c9082',
        'chart-2': '#a0aa88',
        'chart-3': '#8b9d83',
        'chart-4': '#6b7280',
        'chart-5': '#e8e6e1',
        'destructive': '#c73e3a',
        'destructive-foreground': '#ffffff',
        'foreground': '#1a1f2e',
        'input': '#ffffff',
        'muted': '#e8e6e1',
        'muted-foreground': '#6b7280',
        'popover': '#ffffff',
        'popover-foreground': '#1a1f2e',
        'primary': '#7c9082',
        'primary-foreground': '#ffffff',
        'ring': '#7c9082',
        'secondary': '#ced4bf',
        'secondary-foreground': '#1a1f2e',
        sidebar: '#fafaf8',
        'sidebar-accent': '#e8e6e1',
        'sidebar-accent-foreground': '#1a1f2e',
        'sidebar-border': '#e8e6e1',
        'sidebar-foreground': '#1a1f2e',
        'sidebar-primary': '#7c9082',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#7c9082',
      }),
      dark: convertTweakcnToVritti({
        'accent': '#36443a',
        'accent-foreground': '#f5f5f5',
        'background': '#0a0a0a',
        'border': '#2a2a2a',
        'card': '#121212',
        'card-foreground': '#f5f5f5',
        'chart-1': '#7c9082',
        'chart-2': '#a0aa88',
        'chart-3': '#8b9d83',
        'chart-4': '#6b7280',
        'chart-5': '#5a6b5e',
        'destructive': '#ef4444',
        'destructive-foreground': '#ffffff',
        'foreground': '#f5f5f5',
        'input': '#121212',
        'muted': '#1a1a1a',
        'muted-foreground': '#a0a0a0',
        'popover': '#121212',
        'popover-foreground': '#f5f5f5',
        'primary': '#7c9082',
        'primary-foreground': '#000000',
        'ring': '#7c9082',
        'secondary': '#1a1a1a',
        'secondary-foreground': '#f5f5f5',
        sidebar: '#0f0f0f',
        'sidebar-accent': '#1a1a1a',
        'sidebar-accent-foreground': '#f5f5f5',
        'sidebar-border': '#2a2a2a',
        'sidebar-foreground': '#f5f5f5',
        'sidebar-primary': '#7c9082',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-ring': '#7c9082',
      }),
      radius: '0.35rem',
    },
    fonts: {
      sans: 'Antic, ui-sans-serif, sans-serif, system-ui',
      serif: 'Signifier, Georgia, serif',
      mono: 'JetBrains Mono, Courier New, monospace',
    },
    shadow: {
      color: '#1a1f2e',
      opacity: '0.04',
      blur: '2px',
      spread: '0px',
      offsetX: '0px',
      offsetY: '1px',
    },
    letterSpacing: '0em',
    spacing: '0.23rem',
  },
];
